### ISSUE TITLE
Using `markdownItPlugins` throws error

### ISSUE THREAD

**Issue by Crown0815** [DavidAnson/markdownlint-cli2#128]
Hi,

I might be doing something wrong, but using the [default configuration](https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml) causes an exception to be thrown:

```
Error: Cannot find module '@iktakahiro/markdown-it-katex'
Require stack:
- C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js / Cannot find module 'C:\Development\heliOS\docs\@iktakahiro\markdown-it-katex' imported from C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js
    at importOrRequireResolve (C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js:88:11)
    at async Promise.all (index 0)
    at async importOrRequireIdsAndParams (C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js:104:19)
    at async Promise.all (index 1)
    at async createDirInfos (C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js:582:3)
    at async main (C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js:863:5)
    at async C:\Users\kroener\AppData\Roaming\npm\node_modules\markdownlint-cli2\markdownlint-cli2.js:911:26
```

From the documentation, I assumed that in case a module was not installed, it would be automatically installed. Is this incorrect?

**Comment by nschonni** [comment]
That isn't the default config, it's a text fixuture.
Any dependency would need to be installed, packages don't tend to interact with NPM/Yarn on your behalf to pull down packages

**Comment by DavidAnson** [comment]
Yes, the project you are running on defines a custom configuration that references a plug-in that doesn't seem to be available on your system. The project may assume you have installed it globally or you may need to do something like`npm install` for that project. The paths in the error message will help you investigate.
