### ISSUE TITLE
Error: Not supported at enumerateFiles markdownlint-cli2.js:391:22

### ISSUE THREAD

**Issue by JayBeeDe** [DavidAnson/markdownlint-cli2#48]
Hi,
I am newbie with nodeJS and I'm trying to make markdownlint-cli2 working.
I am using debian 10 and I have tried with several version of nodeJS and it's always the same issue when trying to run it on a specific file:

```none
markdownlint-cli2 README.md
markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Finding: README.md
Error: Not supported
    at enumerateFiles (/usr/local/lib/nodejs/node-v9.9.0-linux-x64/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:391:22)
```

I have installed enumerate-files package with npm but it doesn't change anything... Do you have an idea ?

**Comment by DavidAnson** [comment]
You don't need to install anything other than the directions here: https://github.com/DavidAnson/markdownlint-cli2#install

That message sounds like you are on an unsupported version of Node. Please run `node --version` to see what version you have. Supported versions are 12 and later: https://github.com/DavidAnson/markdownlint-cli2/blob/79c5e552066e7ad28aca449e7f2eed692a603abf/package.json#L41

**Comment by JayBeeDe** [comment]
Hi
@DavidAnson yes indeed. Sorry for stupid question.
